name: "Preview Environments for GitHub"
description: "Ephemeral preview deployments of your app for every pull request. Just using Docker Compose. In your AWS account."
author: "Cyril Rohr"
branding:
  icon: anchor
  color: purple
inputs:
  app_path:
    description: "The path to your application containing a docker-compose file"
    default: "/github/workspace"
    required: false
  always_on:
    description: "List of always-on branches, irrespective of whether they correspond to an open Pull Request, comma-separated"
    default: ""
  dns:
    description: "Which DNS suffix to use"
    default: "my.pullpreview.com"
  label:
    description: "Label to use for triggering preview deployments"
    default: "pullpreview"
  github_token:
    description: "The personal access token used to update the status of your commit"
    default: "${{ github.token }}"
  admins:
    description: "Logins of GitHub users that will have their SSH key installed on the instance, comma-separated"
    required: false
    default: "@collaborators/push"
  ports:
    description: "Ports to open for external access on the preview server (port 22 is always open), comma-separated"
    required: false
    default: "80/tcp,443/tcp"
  cidrs:
    description: "The IP address, or range of IP addresses in CIDR notation, that are allowed to connect to the instance"
    required: false
    default: "0.0.0.0/0"
  default_port:
    description: "The port to use when building the preview URL"
    required: false
    default: "80"
  compose_files:
    description: "Compose files to use when running docker-compose up, comma-separated"
    required: false
    default: "docker-compose.yml"
  compose_options:
    description: "Additional options to pass to docker-compose up, comma-separated"
    required: false
    default: "--build"
  license:
    description: "PullPreview license"
    required: false
    default: ""
  instance_type:
    description: "Instance type to use"
    required: false
    default: "small"
  deployment_variant:
    description: "Deployment variant, which allows launching multiple deployments per PR (4 chars max)"
    required: false
    default: ""
  provider:
    description: "Cloud provider to use: lightsail"
    required: false
    default: "lightsail"
  registries:
    description: "Names of private registries to authenticate against. E.g. docker://username:password@ghcr.io"
    required: false
    default: ""
  pre_script:
    description: "Path to a bash script to run on the instance, before calling docker compose, relative to the app_path"
    required: false
    default: ""
  ttl:
    description: "Maximum time to live for deployments (e.g. 10h, 5d, infinite)"
    required: false
    default: "infinite"

outputs:
  url:
    description: "The URL of the application on the preview server"
  host:
    description: "The hostname or IP address of the preview server"
  username:
    description: "The username that can be used to SSH into the preview server"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "github-sync"
    - "${{ inputs.app_path }}"
    - "--admins"
    - "${{ inputs.admins }}"
    - "--cidrs"
    - "${{ inputs.cidrs }}"
    - "--compose-files"
    - "${{ inputs.compose_files }}"
    - "--compose-options"
    - "${{ inputs.compose_options }}"
    - "--dns"
    - "${{ inputs.dns }}"
    - "--label"
    - "${{ inputs.label }}"
    - "--ports"
    - "${{ inputs.ports }}"
    - "--default-port"
    - "${{ inputs.default_port }}"
    - "--always-on"
    - "${{ inputs.always_on }}"
    - "--instance-type"
    - "${{ inputs.instance_type }}"
    - "--deployment-variant"
    - "${{ inputs.deployment_variant }}"
    - "--registries"
    - "${{ inputs.registries }}"
    - "--pre-script"
    - "${{ inputs.pre_script }}"
    - "--ttl"
    - "${{ inputs.ttl }}"
  env:
    GITHUB_TOKEN: "${{ inputs.github_token }}"
    PULLPREVIEW_LICENSE: "${{ inputs.license }}"
    PULLPREVIEW_PROVIDER: "${{ inputs.provider }}"
